sudo: true
language: node_js
node_js:
  - '8'
cache: yarn
addons:
  apt:
    packages:
      - sshpass
install:
  - npm i npminstall && npminstall
script:
  - npm run lint
  - npminstall codecov && codecov